name: cross-root
on: [push]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install python-setuptools pylint3
      - run: pip3 install setuptools pysqlite3
      - run: pylint cross_sysroot

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install pytest
      - run: pip install setuptools pysqlite3
      - run: PYTHONPATH=$PWD pytest

  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install setuptools pysqlite3
      - run: python3 setup.py sdist bdist_wheel || python setup.py sdist bdist_wheel
      # Install the package
      - run: pip install .
      # Try to run it
      - run: cross-sysroot --help

  test_github_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: labapart/cross_sysroot@master
        with:
          distribution: debian
          distribution_version: stable
          architecture: arm64
          build_root: cross-sysroot-tmp
          package_requirements: tests/requirements-debian-jessie-arm64.txt

  pypi_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - run: pip install setuptools pysqlite3
      - name: Install pypa/build
        run: python -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/
      - name: Publish distribution package to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
