name: cross-root
on: [push]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install python-setuptools pylint3
      - run: pip3 install setuptools pysqlite3
      - run: pylint cross_sysroot

  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, pypy2, pypy3]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install pytest
      - run: pip install setuptools pysqlite3
      - run: PYTHONPATH=$PWD pytest

  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install setuptools pysqlite3
      - run: python3 setup.py sdist bdist_wheel || python setup.py sdist bdist_wheel
      # Install the package
      - run: pip install .
      # Try to run it
      - run: cross-sysroot --help

  github_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: labapart/cross_sysroot@master
        with:
          distribution: debian
          distribution_version: stable
          architecture: arm64
          build_root: cross-sysroot-tmp
          package_requirements: tests/requirements-debian-jessie-arm64.txt
